---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  annotations:
    triggers.tekton.dev/old-escape-quotes: 'true'
  name: maven-buildah
spec:
  params:
    - name: app_source_repo_url
    - name: app_source_repo_id
    - name: app_source_repo_branch
    - name: app_source_repo_branch_handled
    - name: app_source_repo_commit_hash
    - name: app_source_repo_commit_hash_full
    - name: app_source_repo_merged_branch_last_commit_hash
    - name: environment_to_deploy
    - name: app_source_repo_path
    - name: url_encoded_app_source_repo_path
    - name: app_name
    - name: project_name
    - name: push_timestamp
    - name: git_protocol
    - name: git_hostname
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.app_name)-$(tt.params.environment_to_deploy)-$(tt.params.app_source_repo_commit_hash)-
      spec:
        pipelineRef:
          name: maven-buildah
        podTemplate:
          volumes:
            - name: maven-repo
              persistentVolumeClaim:
                claimName: maven-repo-pvc
        workspaces:
          - name: main-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 2Gi
        timeouts:
          pipeline: 10h0m0s
        params:
          - name: PROJECT_NAME
            value: $(tt.params.project_name)

          - name: APP_NAME
            value: $(tt.params.app_name)

          - name: ENVIRONMENT_TO_DEPLOY
            value: $(tt.params.environment_to_deploy)

          - name: REGISTRY_URL
            value: 'image-registry.openshift-image-registry.svc:5000'

          - name: GIT_URL
            value: '$(tt.params.git_protocol)$(tt.params.git_hostname)'

          - name: APP_SOURCE_REPO_URL
            value: $(tt.params.app_source_repo_url)

          - name: APP_SOURCE_REPO_PATH
            value: $(tt.params.app_source_repo_path)

          - name: URL_ENCODED_APP_SOURCE_REPO_PATH
            value: $(tt.params.url_encoded_app_source_repo_path)

          - name: APP_SOURCE_REPO_ID
            value: $(tt.params.app_source_repo_id)

          - name: APP_SOURCE_REPO_BRANCH
            value: $(tt.params.app_source_repo_branch)

          - name: APP_SOURCE_REPO_COMMIT_HASH
            value: $(tt.params.app_source_repo_commit_hash)

          - name: APP_SOURCE_REPO_COMMIT_HASH_FULL
            value: $(tt.params.app_source_repo_commit_hash_full)

          - name: APP_SOURCE_REPO_PUSH_TIMESTAMP
            value: $(tt.params.push_timestamp)

          - name: APP_GITOPS_REPO_URL
            value: '$(tt.params.git_protocol)$(tt.params.git_hostname)/gitops/$(tt.params.app_source_repo_path)'
