apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default

  destination:
    name: ocp-homol
    namespace: minio

  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.0.15
    helm:
      values: |
        mode: standalone

        replicas: 1

        rootUser: admin
        rootPassword: supersecret123

        persistence:
          enabled: true
          size: 100Gi

        resources:
          requests:
            cpu: 50m
            memory: 1Gi
          limits:
            cpu: 2
            memory: 4Gi

        service:
          type: ClusterIP

        ingress:
          enabled: false