apiVersion: v1
kind: Secret
metadata:
  name: quay-s3
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  access_key: admin
  secret_key: QmzQsDm3SWC8XRjEO98l2JdzAOeTqJ
  bucket_name: quay
  hostname: minio.minio.svc
  port: "9000"
  is_secure: "false"