apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-gitops
spec:
  params:
    - name: gitopsChanges
      type: array
    - name: environmentToDeploy
      type: string
  workspaces:
    - name: app-source-repo
    - name: app-gitops-repo
  steps:
    - name: execute-gitops-changes
      image: image-registry.openshift-image-registry.svc:5000/openshift/yq
      workingDir: $(workspaces.app-gitops-repo.path)/overlays/$(params.environmentToDeploy)
      script: |
        #!/bin/bash

        set -euox pipefail

        for cmd in "$@"; do
          bash -c "$cmd"
        done
      args:
        - $(params.gitopsChanges[*])
