apiVersion: v1
kind: Secret
metadata:
  name: quay-config-bundle
  namespace: quay
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  config.yaml: |
    AUTHENTICATION_TYPE: Database
    SUPER_USERS:
    - quayadmin
    DEFAULT_TAG_EXPIRATION: 5w
    SERVER_HOSTNAME: quay.apps.ocp-homol.sandbox2414.opentlc.com
    SETUP_COMPLETE: true
    FEATURE_DIRECT_LOGIN: true
    REGISTRY_TITLE: Red Hat Quay
    REGISTRY_TITLE_SHORT: Registro de imagens de container
    TAG_EXPIRATION_OPTIONS:
    - 2w
    - 4w
    - 8w
    - 12w
    TEAM_RESYNC_STALE_TIME: 60m