apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pipelines
  namespace: openshift-gitops
spec:
  description: Projeto para pipelines CI/CD

  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: in-cluster

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'