apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-ca
  namespace: quay
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDfzCCAmegAwIBAgIUXYCCHU+ORby8RK6DN9e8lEE74fEwDQYJKoZIhvcNAQEL
    BQAwKDEmMCQGA1UEAxMdbWluaW8ubWluaW8uc3ZjLmNsdXN0ZXIubG9jYWwwHhcN
    MjYwNTE5MjIxNzE3WhcNMjYwODE3MjIxNzE3WjAoMSYwJAYDVQQDEx1taW5pby5t
    aW5pby5zdmMuY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
    AQoCggEBAM3va1puH2GotHgrED/F2PrKWL47DkoyZSNmlt0KwYkX62eGJY31eFbO
    MibY0HPbvWJ9g8erqBFMtYZpW6/p7HFY2uw6IrD3ORGoLzpA5teJz1c1+nwG9WWK
    WKxUIHp3NQqP2BGmUNqAILLHUczcXviX0OI2LBYtvvjxi1RaPA3fRjjAKJQ2bZuv
    20oXLe97GMDk1IiNNKYBBKwwr8ZCtM7/GgRsrdHzcueQqaNWUDUjanodccP4iCQ1
    B8sEnj2k/SkgVZUTLLEiUmtJxX8NvlUM8A5ju75/BC4m/U/SJkDMeVmxULm2Ew6y
    Zvs/Q6+iWsYIoJonf+4lCV/8TvlhCO0CAwEAAaOBoDCBnTAOBgNVHQ8BAf8EBAMC
    BaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIwADBoBgNVHREEYTBf
    ggVtaW5pb4ILbWluaW8ubWluaW+CD21pbmlvLm1pbmlvLnN2Y4IdbWluaW8ubWlu
    aW8uc3ZjLmNsdXN0ZXIubG9jYWyCGW1pbmlvLmFwcHMuc2V1ZG9taW5pby5jb20w
    DQYJKoZIhvcNAQELBQADggEBAG5Qlnic5tSDYVMOvu6CMngtXSjVSE8mpjFDOkcj
    TdHBvor7u+2PbcLV7ff03P5KH5+OvCCoNEo5MEuPbjEutYzooAKqdHSa7S0t8f+H
    oPindLtydBINSWfvtaTPz1B5jDQQrpNt0UFT0mfY2+93aJs/2BLBC0jSvK2B9fQS
    ivds8HvSj/5Pqd3j5XtVBenfwRG+ague1yV3Tk6nxeCPdSke8vZtF6lXoHipTCy6
    3+RlxdEUsXjzQFU9yV+eV75nvB4eaxOftdy9lualFNWSDAFGz1/4F+4nfbW1v9EO
    3JvrCdMAl8UkvvB+4y9LioqiQddABv/uzQn3BUswNtP2hUw=
    -----END CERTIFICATE-----