apiVersion: v1
kind: Namespace
metadata:
  name: quay
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/node-selector: 'node-role.kubernetes.io/infra='
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator":"Equal","value":"","effect":"NoSchedule","key":"node-role.kubernetes.io/infra"}]'