apiVersion: v1
kind: Secret
metadata:
  name: quay-config-bundle
  namespace: quay
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  config.yaml: |
    AUTHENTICATION_TYPE: Database
    SUPER_USERS:
    - quayadmin
    DEFAULT_TAG_EXPIRATION: 8w
    SERVER_HOSTNAME: quay.apps.ocp-homol.sandbox2671.opentlc.com
    SETUP_COMPLETE: true
    REGISTRY_TITLE: Red Hat Quay
    REGISTRY_TITLE_SHORT: Registro de imagens de container
    TAG_EXPIRATION_OPTIONS:
    - 2w
    - 4w
    - 8w
    - 12w
    TEAM_RESYNC_STALE_TIME: 60m

    DISTRIBUTED_STORAGE_CONFIG:
      default:
        - S3Storage
        - host: minio.minio.svc
          port: 9000
          s3_access_key: admin
          s3_secret_key: QmzQsDm3SWC8XRjEO98l2JdzAOeTqJ
          s3_bucket: quay
          storage_path: /datastorage/registry

    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
    DISTRIBUTED_STORAGE_PREFERENCE:
      - default

    FEATURE_USER_CREATION: true
    EXTERNAL_TLS_TERMINATION: true