---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: generic-buildah
spec:
  params:
    - name: environment_to_deploy
      value: $(extensions.environment_to_deploy)
    - name: app_name
      value: $(extensions.app_name)
    - name: project_name
      value: $(extensions.project_name)
    - name: app_source_repo_url
      value: $(body.repository.git_http_url)
    - name: app_source_repo_id
      value: $(body.project_id)
    - name: app_source_repo_branch
      value: $(extensions.branch_name)
    - name: app_source_repo_branch_handled
      value: $(extensions.branch_name_handled)
    - name: app_source_repo_commit_hash
      value: $(extensions.hash_commit)
    - name: app_source_repo_commit_hash_full
      value: $(body.after)
    - name: push_timestamp
      value: $(body.commits[-1].timestamp)
    - name: app_source_repo_path
      value: $(extensions.app_source_repo_path)
    - name: url_encoded_app_source_repo_path
      value: $(extensions.url_encoded_app_source_repo_path)
    - name: git_protocol
      value: $(extensions.git_protocol)
    - name: git_hostname
      value: $(extensions.git_hostname)
