---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-credentials
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/basic-auth
      metadata:
        annotations:
          tekton.dev/git-0: 'http://git.inep.gov.br'
    name: git-credentials
  dataFrom:
    - extract:
        key: kv/ocp-bmt/gitlab
