---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redhat-pull-secret
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
    name: redhat-pull-secret
  dataFrom:
    - extract:
        key: kv/ocp-bmt/redhat-pull-secret
