---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: service-now-secret
spec:
  refreshInterval: '10s'
  secretStoreRef:
    name: hashicorp-vault
    kind: ClusterSecretStore
  target:
    name: service-now-secret
  dataFrom:
    - extract:
        key: kv/ocp-bmt/service-now-secret
