apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: generic-buildah
spec:
  params:
    - name: GIT_REPO
    - name: GIT_BRANCH

  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: ci-run-
      spec:
        serviceAccountName: pipeline

        pipelineRef:
          name: generic-buildah

        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Gi

        params:
          - name: GIT_REPO
            value: $(tt.params.GIT_REPO)

          - name: GIT_BRANCH
            value: $(tt.params.GIT_BRANCH)