---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: generic-buildah
spec:
  params:
    - name: PROJECT_NAME
      type: string
    - name: APP_NAME
      type: string
    - name: ENVIRONMENT_TO_DEPLOY
      type: string
    - name: REGISTRY_URL
      type: string
    - name: GIT_URL
      type: string
    - name: APP_SOURCE_REPO_URL
      type: string
    - name: APP_SOURCE_REPO_PATH
      type: string
    - name: URL_ENCODED_APP_SOURCE_REPO_PATH
      type: string
    - name: APP_SOURCE_REPO_ID
      type: string
    - name: APP_SOURCE_REPO_BRANCH
      type: string
    - name: APP_SOURCE_REPO_COMMIT_HASH
      type: string
    - name: APP_SOURCE_REPO_COMMIT_HASH_FULL
      type: string
    - name: APP_SOURCE_REPO_PUSH_TIMESTAMP
      type: string
    - name: APP_GITOPS_REPO_URL
      type: string
    - name: PIPELINE_NAME_CAMEL_CASE
      type: string
      default: genericBuildah
    - name: COBUILD_APP_NAME
      type: string
      default: ''
  workspaces:
    - name: main-workspace
  tasks:
    - name: fetch-source-repo
      # when:
      #   - input: "false"
      #     operator: in
      #     values: ["true"]
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      params:
        - name: URL
          value: '$(params.APP_SOURCE_REPO_URL)'
        - name: REVISION
          value: '$(params.APP_SOURCE_REPO_COMMIT_HASH_FULL)'
        - name: deleteExisting
          value: 'true'
      workspaces:
        - name: output
          workspace: main-workspace
          subPath: app-source-repo

    - name: fetch-gitops-repo
      # when:
      #   - input: "false"
      #     operator: in
      #     values: ["true"]
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      params:
        - name: URL
          value: '$(params.APP_GITOPS_REPO_URL)'
        - name: deleteExisting
          value: 'true'
      workspaces:
        - name: output
          workspace: main-workspace
          subPath: app-gitops-repo

    - name: process-tekton-yaml
      # when:
      #   - input: "false"
      #     operator: in
      #     values: ["true"]
      taskRef:
        kind: Task
        name: process-tekton-yaml
      params:
        - name: defaultAppName
          value: '$(params.APP_NAME)'
        - name: defaultProjectName
          value: '$(params.PROJECT_NAME)'
        - name: environmentToDeploy
          value: '$(params.ENVIRONMENT_TO_DEPLOY)'
        - name: registryUrl
          value: '$(params.REGISTRY_URL)'
        - name: appSourceRepoCommitHash
          value: '$(params.APP_SOURCE_REPO_COMMIT_HASH)'
        - name: pipelineNameCamelCase
          value: '$(params.PIPELINE_NAME_CAMEL_CASE)'
        - name: cobuildAppName
          value: '$(params.COBUILD_APP_NAME)'
      workspaces:
        - name: app-source-repo
          workspace: main-workspace
          subPath: app-source-repo
        - name: process-tekton-yaml
          workspace: main-workspace
          subPath: process-tekton-yaml
      runAfter:
        - fetch-source-repo
        - fetch-gitops-repo

    - name: build-image
      # when:
      #   - input: "false"
      #     operator: in
      #     values: ["true"]
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      params:
        - name: IMAGE
          value: $(tasks.process-tekton-yaml.results.fullyQualifiedImageName)
        - name: DOCKERFILE
          value: $(tasks.process-tekton-yaml.results.buildah_containerFileLocation)
        - name: CONTEXT
          value: .
        - name: FORMAT
          value: oci
        - name: BUILD_ARGS
          value:
            - $(tasks.process-tekton-yaml.results.buildah_buildArgs[*])
      workspaces:
        - name: source
          workspace: main-workspace
          subPath: app-source-repo
      runAfter:
        - process-tekton-yaml

    - name: update-gitops
      # when:
      #   - input: "false"
      #     operator: in
      #     values: ["true"]
      taskRef:
        kind: Task
        name: update-gitops
      params:
        - name: gitopsChanges
          value:
            - $(tasks.process-tekton-yaml.results.gitopsChanges[*])
        - name: environmentToDeploy
          value: '$(params.ENVIRONMENT_TO_DEPLOY)'
      workspaces:
        - name: app-source-repo
          workspace: main-workspace
          subPath: app-source-repo
        - name: app-gitops-repo
          workspace: main-workspace
          subPath: app-gitops-repo
      runAfter:
        - build-image

    - name: push-gitops-repo
      # when:
      #   - input: "false"
      #     operator: in
      #     values: ["true"]
      retries: 10
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-cli
          - name: namespace
            value: openshift-pipelines
      params:
        - name: GIT_USER_NAME
          value: OpenShift
        - name: GIT_USER_EMAIL
          value: openshift@redhat.com
        - name: DELETE_EXISTING
          value: 'false'
        - name: GIT_SCRIPT
          value: |
            git fetch origin main:refs/remotes/origin/main
            git checkout -B main origin/main
            git add .
            git status
            git commit -m "[OpenShift Pipelines] Update $(params.ENVIRONMENT_TO_DEPLOY) environment to $(params.APP_SOURCE_REPO_COMMIT_HASH)" || echo "No changes to commit"
            rm -fr ".git/rebase-merge"
            git pull --rebase origin main
            git push origin main
      workspaces:
        - name: source
          workspace: main-workspace
          subPath: app-gitops-repo
      runAfter:
        - update-gitops
    - name: argocd-sync
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: argocd-task-sync-and-wait
          - name: namespace
            value: openshift-pipelines
      params:
        - name: application-name
          value: '$(tasks.process-tekton-yaml.results.argocd_app_name)'
        - name: revision
          value: 'HEAD'
      runAfter:
        - push-gitops-repo
