OpenShift:
  enabled: true
  createSCC: false
  route:
    enabled: true
    host: "sonarqube.apps.ocp-homol.sandbox2671.opentlc.com"
    tls:
      termination: edge

community:
  enabled: true

replicaCount: 1

persistence:
  enabled: true
  size: 100Gi

setAdminPassword:
  passwordSecretName: sonarqube-admin

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 50m
    memory: 128Mi

jvmOpts: "-Xms512m -Xmx512m"
jvmCeOpts: "-Xms512m -Xmx512m"

prometheusExporter:
  enabled: false

prometheusMonitoring:
  podMonitor:
    enabled: false

monitoringPasscode: "define_it" # Password generico para helm chart