apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-homol-minio
  namespace: openshift-gitops
spec:
  project: default

  source:
    repoURL: git@github.com:luissobrinhoeds/gitops.git
    #repoURL: ssh://git@gogs.fsfx.org.br:2222/srvopenshift/ocp-gitops-platform.git
    targetRevision: HEAD
    path: tools/minio/

  destination:
    name: ocp-homol
    namespace: minio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
