nameOverride: minio
fullnameOverride: minio
mode: standalone

replicas: 1

rootUser: admin
rootPassword: QmzQsDm3SWC8XRjEO98l2JdzAOeTqJ

persistence:
  enabled: true
  size: 100Gi

resources:
  requests:
    cpu: 50m
    memory: 1Gi
  limits:
    cpu: 2
    memory: 4Gi

service:
  type: ClusterIP

ingress:
  enabled: false

securityContext:
  enabled: false

buckets:
  - name: quay
    policy: none
    purge: false
    versioning: false

users:
  - accessKey: quay-user
    secretKey: QmzQsDm3SWC8XRjEO98l2JdzAOeTqJ
    policy: readwrite

# tls:
#   enabled: false
#   certSecret: "minio-tls-secret"
#   publicCrt: "tls.crt"
#   privateKey: "tls.key"