---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cobuild-maven-buildah
spec:
  serviceAccountName: pipeline
  triggers:
    - name: push-trigger
      template:
        ref: cobuild-maven-buildah
      bindings:
        - kind: TriggerBinding
          ref: cobuild-maven-buildah
      interceptors:
        - ref:
            kind: ClusterInterceptor
            name: cel
          params:
            - name: overlays
              value:
                - key: branch_name
                  expression: 'body.ref.replace("refs/heads/","")'

                - key: branch_name_handled
                  expression: 'body.ref.lowerAscii().replace("refs/heads/","").replace("/","-")'

                - key: environment_to_deploy
                  expression: 'body.ref.lowerAscii().replace("refs/heads/","").replace("openshift/desenvolvimento","dev").replace("openshift/homologacao","hml").replace("openshift/producao","prd").replace("openshift/judicial","jud").replace("openshift/stress","str").replace("openshift/treinamento","trn").replace("openshift/clone","cln")'

                - key: hash_commit
                  expression: 'body.after.substring(0,8)'

                - key: app_source_repo_path
                  expression: 'body.project.web_url.replace("://","").substring(body.project.web_url.replace("://","").indexOf("/")+1)'

                - key: url_encoded_app_source_repo_path
                  expression: 'body.project.web_url.replace("://","").substring(body.project.web_url.replace("://","").indexOf("/")+1).replace("/","%2F")'

                - key: app_name
                  expression: 'body.project.web_url.replace("://","").substring(body.project.web_url.replace("://","").indexOf("/")+1).substring(body.project.web_url.replace("://","").substring(body.project.web_url.replace("://","").indexOf("/")+1).indexOf("/")+1).replace("/","-").lowerAscii()'

                - key: project_name
                  expression: 'body.project.web_url.replace("://","").substring(body.project.web_url.replace("://","").indexOf("/")+1).substring(0,body.project.web_url.replace("://","").substring(body.project.web_url.replace("://","").indexOf("/")+1).indexOf("/")).replace("/","-").lowerAscii()'

                - key: git_protocol
                  expression: 'body.project.web_url.substring(0, body.project.web_url.indexOf("://") + 3)'

                - key: git_hostname
                  expression: 'body.project.web_url.substring(body.project.web_url.indexOf("://") + 3, body.project.web_url.indexOf("/", body.project.web_url.indexOf("://") + 3))'
