apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: openshift-gitops
spec:
  project: default

  source:
    repoURL: https://sonatype.github.io/helm3-charts/
    chart: nexus-repository-manager
    targetRevision: "*"
    helm:
      values: |
        persistence:
          enabled: true
          storageSize: 20Gi
          storageClass: ocs-storagecluster-ceph-rbd

        service:
          type: ClusterIP

        nexus:
          env:
            - name: INSTALL4J_ADD_VM_PARAMS
              value: "-Xms1g -Xmx2g"
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              memory: "2Gi"
          securityContext:
            fsGroup: null
            runAsUser: null
            runAsGroup: null
          containerSecurityContext: {}
          podSecurityContext: {}
          nodeSelector:
            node-role.kubernetes.io/infra: ""

        tolerations:
          - key: "node-role.kubernetes.io/infra"
            operator: "Exists"
            effect: "NoSchedule"

        serviceAccount:
          create: false
          name: nexus



  destination:
    server: https://kubernetes.default.svc
    namespace: nexus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
