apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: nexus
    repo: https://sonatype.github.io/helm3-charts/
    releaseName: nexus-repository-manager
    namespace: nexus
    valuesFile: values.yaml

resources:
  - route.yaml