apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nexus
  namespace: nexus
spec:
  to:
    kind: Service
    name: nexus-ui
  port:
    targetPort: nexus-ui
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
