statefulset:
  enabled: true

persistence:
  enabled: true
  storageSize: 20Gi

service:
  type: ClusterIP

nexus:
  env:
    - name: INSTALL4J_ADD_VM_PARAMS
      value: "-Xms1g -Xmx2g"

securityContext: {}
containerSecurityContext: {}
podSecurityContext: {}

initContainers: []

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    memory: "2Gi"
