apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: java
spec:
  description: 'Projetos em java'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
