apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/memoryMb: '16384'
    machine.openshift.io/vCPU: '4'
    argocd.argoproj.io/sync-options: Skip=true
  name: ocp-homol-24kpm-worker-0
  namespace: openshift-machine-api
  labels:
    hive.openshift.io/machine-pool: worker
    hive.openshift.io/managed: 'true'
    machine.openshift.io/cluster-api-cluster: ocp-homol-24kpm
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ocp-homol-24kpm
      machine.openshift.io/cluster-api-machineset: ocp-homol-24kpm-worker-0
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ocp-homol-24kpm
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: ocp-homol-24kpm-worker-0
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          numCoresPerSocket: 2
          diskGiB: 120
          snapshot: ''
          userDataSecret:
            name: worker-user-data
          memoryMiB: 16384
          credentialsSecret:
            name: vsphere-cloud-credentials
          network:
            devices:
              - networkName: 10.135.200
          metadata: {}
          numCPUs: 4
          kind: VSphereMachineProviderSpec
          workspace:
            datacenter: FSFX_Ipatinga
            datastore: /FSFX_Ipatinga/datastore/Datastores HMC II OpenShift Pool/VMDATA119_ME5024
            folder: /FSFX_Ipatinga/vm/Servidor de OPENSHIFT POOL #Ajuste na pasta do vCenter
            resourcePool: /FSFX_Ipatinga/host/FSFX - HMC-II/Resources/OPENSHIFT Pool/OCP-HOMOL #Ajuste no nome do pool para maiusculo 
            server: sipavc30v.fsfx.org.br
          template: ocp-homol-24kpm-rhcos-default_domain
          apiVersion: machine.openshift.io/v1beta1